services:
  crawler-service:
    build: .
    container_name: order-management-crawler
    init: true
    ports:
      - "127.0.0.1:5001:5001"
    environment:
      - FLASK_ENV=production
      - BACKEND_API_URL=http://order_management_backend:3000/api
      - DISPLAY=:99
      - CHROME_BIN=/usr/bin/google-chrome
      - CHROME_PATH=/usr/bin/google-chrome
      - CHROMEDRIVER_PATH=/usr/bin/chromedriver
    shm_size: '2gb'
    deploy:
      resources:
        limits:
          memory: 3G
    restart: unless-stopped
    volumes:
      - pandamall_sessions:/app/logs/sessions
    networks:
      - crawler-network

networks:
  crawler-network:
    driver: bridge

volumes:
  pandamall_sessions:
