services:
  crawler-service:
    build: .
    container_name: order-management-crawler
    init: true
    ports:
      - "127.0.0.1:5001:5001"
    environment:
      - FLASK_ENV=production
      - BACKEND_API_URL=http://order_management_backend:3000/api
    shm_size: '1gb'
    deploy:
      resources:
        limits:
          memory: 1.5G
    restart: unless-stopped
    networks:
      - order_management_network

networks:
  order_management_network:
    external: true
    name: orders_backend_order_management_network
